const categories = [
  "Architecture",
  "Art",
  "Biography & Autobiography",
  "Body, Mind & Spirit",
  "Business & Economics",
  "Calendars",
  "Children Fiction",
  "Children Nonfiction",
  "Comics & Graphic Novels",
  "Computers & Internet",
  "Cooking, Food & Wine",
  "Crafts & Hobbies",
  "Design",
  "Drama",
  "Education",
  "Family & Relationships",
  "Fiction",
  "Foreign Language Study",
  "Games",
  "Gardening",
  "Health & Fitness",
  "History & Geography",
  "House & Home",
  "Humor",
  "Language Arts & Disciplines",
  "Law",
  "Literary Collections",
  "Literary Criticism",
  "Mathematics",
  "Medical",
  "Music",
  "Nature & Outdoors",
  "Performing Arts",
  "Pets",
  "Philosophy",
  "Photography",
  "Poetry",
  "Political Science",
  "Psychology",
  "Reference",
  "Religion & Spirituality",
  "Science",
  "Self-Help",
  "Social Science",
  "Sports & Recreation",
  "Stationery",
  "Study Aids",
  "Technology",
  "Toys & Activities",
  "Transportation",
  "True Crime",
  "Tweens Fiction",
  "Tweens Nonfiction",
  "Young Adult Fiction",
  "Young Adult Nonfiction",
];

const bindings = [
  "Activity Set",
  "Board Books",
  "Bonded Leather",
  "Boxed Set",
  "Calendar",
  "Flap Books",
  "Hardcover",
  "Imitation Leather",
  "Library Binding",
  "Paperback",
  "Pocket Books",
  "Pop-Up Books",
  "Puzzles",
  "Soundboard",
  "Spiral",
  "Wire Coil/Wire Combination",
];

export { categories, bindings };
